config/routes.rb
EquiTurns::Application.routes.draw do

  get "equi_turns/index"
  
  resources :users
  resources :auths
  resources :equi_turns
  resources :stocks

  delete "auths" => "auths#destroy"

  root 'equi_turns#index'

end

app/models/equi_turn.rb
class EquiTurn
  include Mongoid::Document
  field :name, type: String
  field :symbol, type: String
  field :owned, type: Boolean
  field :today, type: Integer
end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document

  attr_accessor :password, :password_confirmation

  field :username, type: String
  field :salt, type: String
  field :hashed_password, type: String
  field :email_address, type: String

  before_save :hash_stuff

  def check_password(pwd)
  	self.hashed_password == BCrypt::Engine.hash_secret(
  		pwd, self.salt)
  end

private
  def hash_stuff
  	self.salt = BCrypt::Engine.generate_salt
  	self.hashed_password = BCrypt::Engine.hash_secret(
  			password, self.salt)
  	password = password_confirmation = nil
  end

end

app/models/zstock.rb
# require 'yahoo_finance'

class Zstock
  include Mongoid::Document

  field :stock, type: String
  field :name, type: String
  field :price, type: Integer
  field :change, type: Integer
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	if session[:user_id]
  		User.find_by(id: session[:user_id]) rescue nil
  	end
  end

  def login_required
  	unless current_user
  		flash[:error] = "You must be logged in to do that!"
  		redirect_to root_path
  	end
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	def new
		if current_user
			redirect_to root_path
		else 
			@user=User.new
		end	
	end

	def create
		if !(User.where(username: params[:user][:username]).empty?)
			@user = User.find_by(username: params[:user][:username])
			if @user.check_password(params[:user][:password])
				session[:user_id] = @user.id
				redirect_to root_path 
			else 
				redirect_to 'new'
			end
				else
					@user = User.new(username: params[:user][:username])
					render new_auth_path
				
		end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_path
	end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  
  def index
  	@episodes = Episode.all
  end
  
end

app/controllers/equi_turns_controller.rb
class EquiTurnsController < ApplicationController
  # before_action :set_equi_turn, only: [:show, :edit, :update, :destroy]

 
  def index
    @equi_turns = EquiTurn.all
    @user = User.new
  end

  def show
    @equi_turn = EquiTurn.find(params[:id])
  end

 
  def new
    @equi_turn = EquiTurn.new
  end

  
  def edit
    @equi_turn = EquiTurn.find(params[:id])
  end

 
  def create
    @equi_turn = EquiTurn.new(equi_turn_params)

      if @equi_turn.save
        flash[:notice] = "Equi_turn was successfully created."
        redirect_to action: 'index'
      else
        render action: 'new' 
      end
  end


  def update
    @equi_turn = EquiTurn.find(params[:id])

      if @equi_turn.update_attributes(equi_turn_params)
        flash[:notice] = "Equi_turn was successfully updated."
        redirect_to action: 'index'
      else
        render action: 'edit'
      end
  end

 
  def destroy
    @equi_turn = EquiTurn.find(params[:id])
      @equi_turn.destroy
      redirect_to action: 'index'
  end

  private

    def equi_turn_params
      params.require(:equi_turn).permit(:name, :symbol, :owned, :today)
    end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

	def show
	    @stock = Stock.find(params[:id])
	    all_info = StockQuote::Stock.quote(@stock.ticker)
	    @name = all_info.name.split[0]
	    @price = all_info.ask_realtime
	    @change = all_info.change_realtime
	end

	def index
	    @stocks = StockQuote::Stock.quote("VZ, BAC, CSCO, MSF")
	end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if (@user.save)
			redirect_to action: 'index'
		else
			render "new"
		end
	end

private

    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		User.create(params.require(:user).permit(:username, :password))
		redirect_to action: 'index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equi_turns_helper.rb
module EquiTurnsHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/auths/new.html.erb
<div id="login" class="container">
	<h3 class="header">sign in</h3>
	<%= form_for @user, {url:"/auths", method:"post"} do |u|%>
	<%= u.text_field :username, :placeholder => "Your username", class:"margin" %><br>
	<%= u.password_field :password, :placeholder => "Your password", class:"margin" %><br>
	<%= u.submit "Log In", class:"margin"%>
	<%end%>
<br />
	<%= link_to "back to EquiTurns", root_path %>
</div>

app/views/equi_turns/_form.html.erb
<%= form_for(@equi_turn) do |f| %>
  <% if @equi_turn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equi_turn.errors.count, "error") %> prohibited this equi_turn from being saved:</h2>

      <ul>
      <% @equi_turn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>


      <div>
        <%= f.label :symbol %><br />
        <%= f.select :symbol, ['BAC', 'MSF', 'CSCO', 'VZ'] %>
      </div>

      <div>
        <%= f.label :owned %><br />
        <%= f.check_box :owned %>
      </div>

      <div>
        <%= f.label :today %><br />
        <%= f.text_field :today %>
      </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equi_turns/edit.html.erb
<h1>Editing EquiTurn</h1>

<%= render 'form' %>

<%= link_to 'Show', @equi_turn %> |
<%= link_to 'Back', equi_turns_path %>

app/views/equi_turns/index.html.erb
<head>
  <title>EquiTurns</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "equi_turns", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="carousel slide" id="myCarousel">

     <!--  Indicators -->
     <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#myCarousel"></li>
        <li data-slide-to="1" data-target="#myCarousel"></li>
     </ol>
      <!--   Wrapper for slides -->
      <div class="carousel-inner">
        
          <div class="item active" id="slide1">
            <div class="carousel-caption">
              <h4>Text Heading</h4>
              <p>Finance text style to each other.</p>
            </div> <!-- end carousel-caption -->
          </div><!--  end item -->

          <div class="item" id="slide2">
            <div class="carousel-caption">
              <h4>Text Heading 2</h4>
              <p>Finance for coffee.</p>
            </div> <!-- end carousel-caption -->
          </div><!--  end item -->

      </div> <!-- carousel-inner -->

      <!-- Control -->
      <a class="left carousel-control" data-slide="prev" href="#myCarousel"><span class="icon-prev"></span></a>
      <a class="right carousel-control" data-slide="next" href="#myCarousel"><span class="icon-next"></span></a>

  </div><!--  end myCarousel -->

  <div class="row" id="bigCallout">
      <div class="col-12">
        <div class="well well-small visible-sm">
            <a href="" class="btn btn-large btn-block btn-default"><span class="glyphicon glyphicon-phone"></span> Give us a Call </a>
        </div> <!-- end well small -->
        <div class="well">
            <div class="page-header">
              <h1> All About Returns <small> See How It Works</small></h1>
            </div> <!-- end page-header -->
            <p class="lead">Fast, Easy, Free...financial resource available to you today...take control of your future</p>
        </div> <!-- end well -->

      </div> <!-- end col-12 -->

  </div><!--- end bigCallout -->

  <h2>Current Portfolio</h2>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Symbol</th>
          <th>Owned</th>
          <th>today</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @equi_turns.each do |equi_turn| %>
          <tr>
            <td><%= equi_turn.name %></td>
            <td><%= equi_turn.symbol %></td>
            <td><%= equi_turn.owned %></td>
            <td><%= equi_turn.today %></td>
            <td><%= link_to 'Show', equi_turn_path(equi_turn) %></td>
            <td><%= link_to 'Edit', edit_equi_turn_path(equi_turn) %></td>
            <td><%= link_to 'Destroy', equi_turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
        <% end %>
      </tbody>

  </table>
      <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        See Current Stocks
      </button>

      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">See Returns</h4>
            </div>
            <div class="modal-body">
             <%=image_tag("returns.jpg", class: "img-thumbnail", alt: "RETURN") %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>

  <%= link_to 'or Add New Stock', new_equi_turn_path, class: "link" %>

  <div class="row">
    <%=image_tag("black.jpg", class: "img-thumbnail black", alt: "RETURN") %>
        <div class="col-xs-6 col-md-2 col-lg-3"><%=image_tag("bluestock.jpg", class: "img-circle blue", alt: "RETURN") %></div>
        <div class="col-xs-6 col-md-2 col-lg-3"><%=image_tag("green.jpg", class: "img-circle green", alt: "RETURN") %></div>
        <div class="col-xs-6 col-md-2 col-lg-3"><%=image_tag("multi.jpg", class: "img-circle multi", alt: "RETURN") %></div>
        <div class="col-xs-6 col-md-2 col-lg-3"><%=image_tag("greenstock.jpg", class: "img-circle gstock", alt: "RETURN") %></div>
  </div> 

      <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        See Returns
      </button>
</body>
  

app/views/equi_turns/new.html.erb
<h1>New EquiTurn</h1>

<%= render 'form' %>

<%= link_to 'Back', equi_turns_path %>

app/views/equi_turns/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_equi_turn_path(@equi_turn) %> |
<%= link_to 'Back', equi_turns_path %>

app/views/layouts/_nav.html.erb
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="/assets/EquiLogo.jpg" class="equilogo", alt="Your logo"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
   
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group"><span class="glyphicon glyphicon-search"></span>
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
     
      <ul class="nav navbar-nav navbar-right">
        <% if current_user == nil %>
          <li><%= link_to "Login", new_auth_path %></li>
          <li><%= link_to "Create User", new_user_path %></li>
        <%end%>
          <li><%= link_to "Logout", auths_path, method: :delete %></li>
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EquiTurns</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "equi_turns", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header></header>
	<nav class="navbar navbar-default" role="navigation">
		<%= render partial: 'layouts/nav' %>
	</nav>

<%= yield %>

</body>
</html>

app/views/stocks/index.html.erb
<h1>Stock Portfolio</h1>

</ul>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Ask</th>
          <th>Change</th>
          <th>PE</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td><%= stock.name %></td>
            <td><%= stock.ask %></td>
            <td><%= stock.change %></td>
            <td><%= stock.pe_ratio %></td>
          </tr>
        <% end %>
      </tbody>

  </table>

app/views/users/index.html.erb
<h1>List of Users</h1>
    <ul>
      <% @users.each do |user| %>
         <li><%= user.username %></li>
      <% end %>
    </ul>

app/views/users/new.html.erb
<% if current_user %>
	You're already logged in!!
<% end %>

<div class="createuser">
	<h1>Create a New User</h1>
		<%=form_for @user do |f|%>
				<%=f.text_field :username, :placeholder => "Enter your username"%><br>
				<%=f.password_field :password, :placeholder => "Enter password" %><br>
			<%= f.submit "Create New User" %>
		<% end %>
</div>